@startuml overview
top to bottom direction
skinparam linetype ortho

component database
component frontend
component request
component response

component User
component UserController
component UserService
component UserRepository
UserController - UserService
UserService - UserRepository
UserService .. User
UserRepository .. User
UserRepository -- database

component Post
component PostController
component PostService
component PostRepository
PostController - PostService
PostService - PostRepository
PostService .. Post
PostRepository .. Post
PostRepository -- database

PostController -- UserService

component Comment
component CommentController
component CommentService
component CommentRepository
CommentController - CommentService
CommentService - CommentRepository
CommentService .. Comment
CommentRepository .. Comment
CommentRepository -- database

CommentController -- UserService
CommentController -- PostService

component Destination
component DestinationController
component DestinationService
component DestinationRepository
DestinationController - DestinationService
DestinationService - DestinationRepository
DestinationService .. Destination
DestinationRepository .. Destination
DestinationRepository -- database

DestinationController -- UserService

frontend - UserController
frontend - PostController
frontend - CommentController
frontend - DestinationController

request -- UserController
request -- PostController
request -- CommentController
request -- DestinationController

response -- UserController
response -- PostController
response -- CommentController
response -- DestinationController

@enduml