@startuml post

' !theme plain
top to bottom direction
skinparam linetype ortho

class Post {
  - comments: List<Comment>
  - id: Long
  - user: User
  - title: String
  - content: String
  - images: List<PostImage>
   content: String
   comments: List<Comment>
   title: String
   id: Long
   user: User
   images: List<PostImage>
  # canEqual(Object): boolean
  + hashCode(): int
  + toString(): String
  + equals(Object): boolean
  + Post(): 
}
class PostController {
   allPosts: ResponseEntity<List<GetResponse>>
  + addPost(String, String, String, List<MultipartFile>): ResponseEntity<Post>
  + PostController(PostService, UserService): 
}
class PostImage {
  - id: Long
  - url: String
  - post: Post
   post: Post
   id: Long
   url: String
  # canEqual(Object): boolean
  + equals(Object): boolean
  + hashCode(): int
  + toString(): String
  + PostImage(): 
}
interface PostRepository << interface >>
class PostService {
   allPosts: List<Post>
  + getPostById(Long): Post
  + savePost(Post): void
  + PostService(PostRepository): 
}

Post           "1" *-[#595959,plain]-> "images\n*" PostImage      
PostController  -[#595959,dashed]->  Post           : "«create»"
PostController  -[#595959,dashed]->  PostController 
PostController  -[#595959,dashed]->  PostImage      : "«create»"
PostController "1" *-[#595959,plain]-> "postService\n1" PostService    
PostImage      "1" *-[#595959,plain]-> "post\n1" Post           
PostRepository  -[#595959,dashed]->  Post           
PostService     -[#595959,dashed]->  Post           
PostService    "1" *-[#595959,plain]-> "postRepository\n1" PostRepository 
@enduml
